
# 预演环境

online: true        # 线上才验证登录
permission: false   # 验证权限吗?
notShowError: false # 不显示错误信息吗?


logging.config: classpath:log-test.xml

server.port: 7015


spring:
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  http.multipart:
    maxFileSize: 12Mb
    maxRequestSize: 20Mb

spring.dubbo:
  scan: com.tudou
  application:
    name: web-platform
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 10000
      register: false

#阿里云OSS配置信息
aliyun.oss:
  access-key-id: access-key-id
  access-key-secret: access-key-secret
  bucket-name: bucket-name
  folder-name: folder-name
  endpoint: endpoint
  image-domain: image-domain
  thumb-domain: thumb-domain
